# Module 1 Homework

### Q1 Pandas version

What version of Pandas did you install?

- 2.3.2

In [1]:
import numpy as np

In [2]:
import pandas as pd

pd.__version__

'2.3.2'

### Getting the data

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q2. Records count

How many records are in the dataset?

- 9704

In [4]:
# How many records are in the dataset?

df.shape

(9704, 11)

### Q3. Fuel types

How many fuel types are presented in the dataset?

- 2

In [5]:
# How many fuel types are presented in the dataset?

df.fuel_type.nunique()

2

### Q4. Missing values

How many columns in the dataset have missing values?

- 4

In [6]:
# How many columns in the dataset have missing values?

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [7]:
df.isna().any().sum()

4

### Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

- 23.759122836520497 (or ~23,76)

In [8]:
df.groupby('origin').max('fuel_efficiency_mpg')['fuel_efficiency_mpg']

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

In [9]:
df.query("origin == 'Asia'").fuel_efficiency_mpg.max()

23.759122836520497

### Q6. Median value of horsepower

1. Find the median value of the horsepower column in the dataset.
- 149.0
2. Next, calculate the most frequent value of the same horsepower column.
- 152.0
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
- okay
4. Now, calculate the median value of horsepower once again. <br>
Has it changed?

- Yes, it increased



In [10]:
# Has it changed?
# 1.

df.horsepower.median()

149.0

In [11]:
# 2.

horsepower_mode = df.horsepower.mode()[0]
horsepower_mode

152.0

In [12]:
# 3.

df['horsepower'] = df['horsepower'].fillna(horsepower_mode)

In [13]:
# 4.

df.horsepower.median()

152.0

### Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

- 0.5187709081074025 (or ~ 0.52)

In [14]:
# 1. Select all the cars from Asia

df_asia = df[df['origin']=="Asia"]
df_asia.origin.unique()

array(['Asia'], dtype=object)

In [15]:
# 2. Select only columns vehicle_weight and model_year

df_asia_vh_my = df_asia[['vehicle_weight', 'model_year']]
df_asia_vh_my.columns

Index(['vehicle_weight', 'model_year'], dtype='object')

In [16]:
# 3. Select the first 7 values

df_asia_selected_7 = df_asia_vh_my.head(7)
df_asia_selected_7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [17]:
# 4. Get the underlying NumPy array. Let's call it X.

X = df_asia_selected_7.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [18]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X. 
# To get the transpose, use X.T. Let's call the result XTX.

XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [19]:
# 6. Invert XTX.

XTX_inv = np.linalg.inv(XTX)
XTX_inv


array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [20]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [21]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = np.dot(XTX_inv,X.T)
w = w.dot(y)
w

array([0.01386421, 0.5049067 ])

In [22]:
# 9. What's the sum of all the elements of the result?

result = sum(w)
result

0.5187709081074025